Create table CUSTOMER (
CID INT (10) PRIMARY KEY AUTO_INCREMENT,
FName VARCHAR (30) NOT NULL,
LName VARCHAR (30) NOT NULL,
Email VARCHAR (30),
Address VARCHAR (50),
Phone INT (10),
Status VARCHAR (5));

Create table PRODUCT (
PID INT (10) PRIMARY KEY AUTO_INCREMENT,
PType VARCHAR (5) NOT NULL,
PName VARCHAR (30) NOT NULL,
PPrice INT (5),
Description VARCHAR (50),
PQuantity INT (5));

Create table CREDIT_CARD (
CCNumber VARCHAR (16) PRIMARY KEY,
SecNumber INT (3) NOT NULL,
OwnerName VARCHAR (20) NOT NULL,
CCType VARCHAR(10) NOT NULL,
BilAddress VARCHAR(50) NOT NULL,
ExpDate Date NOT NULL,
StoredCardCID INT(10),
FOREIGN KEY (StoredCardCID) REFERENCES CUSTOMER(CID);


Create table SILVER_AND_ABOVE (
CID INT(10) NOT NULL,
CreditLine DECIMAL NOT NULL,
PRIMARY KEY(CID),
FOREIGN KEY (CID) REFERENCES CUSTOMER(CID));


Create table SHIPPING_ADDRESS (
CID INT(10) NOT NULL,
SAName VARCHAR(20) NOT NULL,
RecepientName VARCHAR(20) NOT NULL,
Street VARCHAR(20) NOT NULL,
SNumber INT(5) NOT NULL,
City VARCHAR(20) NOT NULL,
Zip VARCHAR(5) NOT NULL,
State VARCHAR(20) NOT NULL,
Country VARCHAR(20) NOT NULL,
PRIMARY KEY(CID, SAName),
FOREIGN KEY (CID) REFERENCES CUSTOMER(CID));


Create table TRANSACTION (
BID INT(10) AUTO_INCREMENT,
CID INT(10) NOT NULL,
SAName VARCHAR(20),
CCNumber VARCHAR (16),
TTag VARCHAR(15),
TDate Date,
PRIMARY KEY (BID,CCNumber,CID,SAName),
FOREIGN KEY (BID) REFERENCES BASKET(BID),
FOREIGN KEY (CCNumber) REFERENCES CREDIT_CARD(CCNumber),
FOREIGN KEY (CID) REFERENCES SILVER_AND_ABOVE(CID),
FOREIGN KEY (CID,SAName) REFERENCES SHIPPING_ADDRESS(CID,SAName));

Create table BASKET (
BID INT(10) PRIMARY KEY AUTO_INCREMENT,
CID INT(10),
FOREIGN KEY (CID) REFERENCES CUSTOMER(CID));


Create table OFFER_PRODUCT (
PID INT (10) PRIMARY KEY,
OfferPrice DECIMAL NOT NULL,
FOREIGN KEY (PID) REFERENCES PRODUCT(PID));


Create table APPEARS_IN (
BID INT(10) NOT NULL,
PID INT(10) NOT NULL,
Quantity INT(5) NOT NULL,
PriceSold DECIMAL NOT NULL,
PRIMARY KEY(PID, BID),
FOREIGN KEY (PID) REFERENCES PRODUCT(PID),
FOREIGN KEY (BID) REFERENCES BASKET(BID));


Create table COMPUTER (
PID INT (10) PRIMARY KEY,
CPUType VARCHAR(20) NOT NULL,
FOREIGN KEY (PID) REFERENCES PRODUCT(PID));

Create table LAPTOP (
PID INT (10) PRIMARY KEY,
BType VARCHAR(20) NOT NULL,
Weight DECIMAL NOT NULL,
FOREIGN KEY (PID) REFERENCES COMPUTER(PID));

Create table PRINTER (
PID INT (10) PRIMARY KEY,
PrinterType VARCHAR(20) NOT NULL,
Resolution VARCHAR(20) NOT NULL,
FOREIGN KEY (PID) REFERENCES PRODUCT(PID));
